# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/cramore
pkgincludedir = $(includedir)/cramore
pkglibdir = $(libdir)/cramore
pkglibexecdir = $(libexecdir)/cramore
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = cramore$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_with_htslib.m4 \
	$(top_srcdir)/m4/hts_prog_cc_warnings.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(noinst_HEADERS) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = config.mk
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_cramore_OBJECTS = cramore.$(OBJEXT) Error.$(OBJEXT) \
	PhredHelper.$(OBJEXT) params.$(OBJEXT) commands.$(OBJEXT) \
	dropseq.$(OBJEXT) hts_utils.$(OBJEXT) \
	bcf_ordered_reader.$(OBJEXT) interval.$(OBJEXT) \
	interval_tree.$(OBJEXT) utils.$(OBJEXT) \
	genome_interval.$(OBJEXT) log_tool.$(OBJEXT) \
	estimator.$(OBJEXT) bcf_ordered_writer.$(OBJEXT) \
	reference_sequence.$(OBJEXT) bcf_chunked_reader.$(OBJEXT) \
	genomeChunk.$(OBJEXT) bcf_filtered_reader.$(OBJEXT) \
	bam_ordered_reader.$(OBJEXT) nuclear_pedigree.$(OBJEXT) \
	genotype_concordance.$(OBJEXT) filter.$(OBJEXT) \
	libsvm.$(OBJEXT) libsvm_gkm.$(OBJEXT) \
	cmd_bed_delta_svm_train.$(OBJEXT) \
	cmd_bed_matched_shuffle.$(OBJEXT) cmd_bed_shuffle.$(OBJEXT) \
	cmd_vcf_mendel_dup_conc.$(OBJEXT) \
	cmd_vcf_sample_summary.$(OBJEXT) cmd_vcf_squeeze.$(OBJEXT) \
	cmd_vcf_delta_svm.$(OBJEXT) cmd_vcf_extract.$(OBJEXT) \
	cmd_vcf_svd.$(OBJEXT) tsv_reader.$(OBJEXT) \
	cmd_cram_simul_contam.$(OBJEXT) \
	cmd_cram_verify_pair_id.$(OBJEXT) \
	cmd_cram_sparse_genotype.$(OBJEXT) cmd_cram_flagstat.$(OBJEXT) \
	cmd_cram_procap_detect.$(OBJEXT) \
	cmd_cram_context_indel_analysis.$(OBJEXT) \
	cmd_sc_multinom_em.$(OBJEXT) cmd_sc_multinom_gibbs.$(OBJEXT) \
	cmd_sc_map_stamps.$(OBJEXT) cmd_sc_kallisto_count.$(OBJEXT) \
	Sort.$(OBJEXT) MathVector.$(OBJEXT) MathGold.$(OBJEXT) \
	MathGenMin.$(OBJEXT) MathMatrix.$(OBJEXT) Random.$(OBJEXT) \
	cmd_vcf_infer_ancestry.$(OBJEXT) ancestry_estimator.$(OBJEXT) \
	cmd_vcf_infer_isaf.$(OBJEXT) frequency_estimator.$(OBJEXT) \
	cmd_vcf_update_sites.$(OBJEXT) sam_filtered_reader.$(OBJEXT) \
	sc_drop_seq.$(OBJEXT) sam_ordered_writer.$(OBJEXT) \
	cmd_cram_simuxlet.$(OBJEXT) cmd_cram_mux_pileup.$(OBJEXT) \
	cmd_cram_dense_genotype.$(OBJEXT) \
	joint_genotype_block_reader.$(OBJEXT) \
	joint_genotype_block_record.$(OBJEXT) variant.$(OBJEXT) \
	variant_manip.$(OBJEXT) augmented_bam_record.$(OBJEXT) \
	sex_ploidy_map.$(OBJEXT) allele.$(OBJEXT) vntr.$(OBJEXT) \
	cmd_fasta_gc_content.$(OBJEXT) fastaGC.$(OBJEXT) \
	cmd_vcf_normalize_depth.$(OBJEXT) cmd_bgen_to_vcf.$(OBJEXT) \
	cmd_cram_verify_bam.$(OBJEXT) contam_estimator.$(OBJEXT) \
	cmd_cram_demuxlet.$(OBJEXT) cmd_vcf_paste_calls.$(OBJEXT) \
	cmd_vcf_merge_candidate_variants.$(OBJEXT) \
	cmd_cram_update_rg.$(OBJEXT) cmd_cram_gtf_util.$(OBJEXT) \
	gtf.$(OBJEXT) cmd_cram_digital_pileup.$(OBJEXT) \
	cmd_cram_freemuxlet.$(OBJEXT)
cramore_OBJECTS = $(am_cramore_OBJECTS)
am__DEPENDENCIES_1 =
am__DEPENDENCIES_2 = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(HTSLIB)
cramore_DEPENDENCIES = $(am__DEPENDENCIES_2) $(am__DEPENDENCIES_1)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/Error.Po ./$(DEPDIR)/MathGenMin.Po \
	./$(DEPDIR)/MathGold.Po ./$(DEPDIR)/MathMatrix.Po \
	./$(DEPDIR)/MathVector.Po ./$(DEPDIR)/PhredHelper.Po \
	./$(DEPDIR)/Random.Po ./$(DEPDIR)/Sort.Po \
	./$(DEPDIR)/allele.Po ./$(DEPDIR)/ancestry_estimator.Po \
	./$(DEPDIR)/augmented_bam_record.Po \
	./$(DEPDIR)/bam_ordered_reader.Po \
	./$(DEPDIR)/bcf_chunked_reader.Po \
	./$(DEPDIR)/bcf_filtered_reader.Po \
	./$(DEPDIR)/bcf_ordered_reader.Po \
	./$(DEPDIR)/bcf_ordered_writer.Po \
	./$(DEPDIR)/cmd_bed_delta_svm_train.Po \
	./$(DEPDIR)/cmd_bed_matched_shuffle.Po \
	./$(DEPDIR)/cmd_bed_shuffle.Po ./$(DEPDIR)/cmd_bgen_to_vcf.Po \
	./$(DEPDIR)/cmd_cram_context_indel_analysis.Po \
	./$(DEPDIR)/cmd_cram_demuxlet.Po \
	./$(DEPDIR)/cmd_cram_dense_genotype.Po \
	./$(DEPDIR)/cmd_cram_digital_pileup.Po \
	./$(DEPDIR)/cmd_cram_flagstat.Po \
	./$(DEPDIR)/cmd_cram_freemuxlet.Po \
	./$(DEPDIR)/cmd_cram_gtf_util.Po \
	./$(DEPDIR)/cmd_cram_mux_pileup.Po \
	./$(DEPDIR)/cmd_cram_procap_detect.Po \
	./$(DEPDIR)/cmd_cram_simul_contam.Po \
	./$(DEPDIR)/cmd_cram_simuxlet.Po \
	./$(DEPDIR)/cmd_cram_sparse_genotype.Po \
	./$(DEPDIR)/cmd_cram_update_rg.Po \
	./$(DEPDIR)/cmd_cram_verify_bam.Po \
	./$(DEPDIR)/cmd_cram_verify_pair_id.Po \
	./$(DEPDIR)/cmd_fasta_gc_content.Po \
	./$(DEPDIR)/cmd_sc_kallisto_count.Po \
	./$(DEPDIR)/cmd_sc_map_stamps.Po \
	./$(DEPDIR)/cmd_sc_multinom_em.Po \
	./$(DEPDIR)/cmd_sc_multinom_gibbs.Po \
	./$(DEPDIR)/cmd_vcf_delta_svm.Po \
	./$(DEPDIR)/cmd_vcf_extract.Po \
	./$(DEPDIR)/cmd_vcf_infer_ancestry.Po \
	./$(DEPDIR)/cmd_vcf_infer_isaf.Po \
	./$(DEPDIR)/cmd_vcf_mendel_dup_conc.Po \
	./$(DEPDIR)/cmd_vcf_merge_candidate_variants.Po \
	./$(DEPDIR)/cmd_vcf_normalize_depth.Po \
	./$(DEPDIR)/cmd_vcf_paste_calls.Po \
	./$(DEPDIR)/cmd_vcf_sample_summary.Po \
	./$(DEPDIR)/cmd_vcf_squeeze.Po ./$(DEPDIR)/cmd_vcf_svd.Po \
	./$(DEPDIR)/cmd_vcf_update_sites.Po ./$(DEPDIR)/commands.Po \
	./$(DEPDIR)/contam_estimator.Po ./$(DEPDIR)/cramore.Po \
	./$(DEPDIR)/dropseq.Po ./$(DEPDIR)/estimator.Po \
	./$(DEPDIR)/fastaGC.Po ./$(DEPDIR)/filter.Po \
	./$(DEPDIR)/frequency_estimator.Po ./$(DEPDIR)/genomeChunk.Po \
	./$(DEPDIR)/genome_interval.Po \
	./$(DEPDIR)/genotype_concordance.Po ./$(DEPDIR)/gtf.Po \
	./$(DEPDIR)/hts_utils.Po ./$(DEPDIR)/interval.Po \
	./$(DEPDIR)/interval_tree.Po \
	./$(DEPDIR)/joint_genotype_block_reader.Po \
	./$(DEPDIR)/joint_genotype_block_record.Po \
	./$(DEPDIR)/libsvm.Po ./$(DEPDIR)/libsvm_gkm.Po \
	./$(DEPDIR)/log_tool.Po ./$(DEPDIR)/nuclear_pedigree.Po \
	./$(DEPDIR)/params.Po ./$(DEPDIR)/reference_sequence.Po \
	./$(DEPDIR)/sam_filtered_reader.Po \
	./$(DEPDIR)/sam_ordered_writer.Po ./$(DEPDIR)/sc_drop_seq.Po \
	./$(DEPDIR)/sex_ploidy_map.Po ./$(DEPDIR)/tsv_reader.Po \
	./$(DEPDIR)/utils.Po ./$(DEPDIR)/variant.Po \
	./$(DEPDIR)/variant_manip.Po ./$(DEPDIR)/vntr.Po
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(cramore_SOURCES)
DIST_SOURCES = $(cramore_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(srcdir)/config.mk.in AUTHORS COPYING ChangeLog INSTALL NEWS \
	README compile depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/hmkang/code/git/cramore/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /Users/hmkang/code/git/cramore/missing autoconf
AUTOHEADER = ${SHELL} /Users/hmkang/code/git/cramore/missing autoheader
AUTOMAKE = ${SHELL} /Users/hmkang/code/git/cramore/missing automake-1.16
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
HTSDIR = ../htslib
HTSLIB_CPPFLAGS = -I../htslib
HTSLIB_LDFLAGS = -L../htslib
Hinstall = #
Hsource = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS =  ${LIBOBJDIR}error$U.o
LIBS = -lz 
LTLIBOBJS =  ${LIBOBJDIR}error$U.lo
MAKEINFO = ${SHELL} /Users/hmkang/code/git/cramore/missing makeinfo
MKDIR_P = ./install-sh -c -d
OBJEXT = o
PACKAGE = cramore
PACKAGE_BUGREPORT = hmkang@umich.edu
PACKAGE_NAME = cramore
PACKAGE_STRING = cramore 3d6ce13-dirty
PACKAGE_TARNAME = cramore
PACKAGE_URL = 
PACKAGE_VERSION = 3d6ce13-dirty
PATH_SEPARATOR = :
POW_LIB = 
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 3d6ce13-dirty
abs_builddir = /Users/hmkang/code/git/cramore
abs_srcdir = /Users/hmkang/code/git/cramore
abs_top_builddir = /Users/hmkang/code/git/cramore
abs_top_srcdir = /Users/hmkang/code/git/cramore
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
include_htslib_mk = include $(HTSDIR)/htslib.mk
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/hmkang/code/git/cramore/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs = 
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4 ${ACLOCAL_FLAGS}

# Usually config.mk and config.h are generated by running configure
# or config.status, but if those aren't used create defaults here.
#config.mk:
#	@sed -e '/^prefix/,/^PLUGIN_EXT/d;s///;s/#/#/;s#../htslib#../htslib#g;s/-I../htslib/-I$$(HTSDIR)/g#;' config.mk.in > $@
#
#config.h:
#	echo '/* Basic config.h generated by Makefile */' > $@
HTSLIB = $(HTSDIR)/libhts.a

#include $(HTSDIR)/htslib.mk
ALL_CPPFLAGS = -I. $(HTSLIB_CPPFLAGS) $(CPPFLAGS)
ALL_LDFLAGS = $(HTSLIB_LDFLAGS) $(LDFLAGS) $(HTSLIB)
ALL_LIBS = -lz -ldl -lpthread -llzma -lz -lbz2  -lcurl -lcrypto
AM_CPPFLAGS = -std=c++11 -pipe -D__STDC_LIMIT_MACROS -Wall -Wno-unused-local-typedefs -Wno-enum-compare -fpic -O2 $(ALL_CPPFLAGS)
EIGEN_HEADER_FILES = Eigen/Cholesky Eigen/CholmodSupport Eigen/Core \
	Eigen/Dense Eigen/Eigen Eigen/Eigenvalues Eigen/Geometry \
	Eigen/Householder Eigen/IterativeLinearSolvers Eigen/Jacobi \
	Eigen/LU Eigen/MetisSupport Eigen/OrderingMethods \
	Eigen/PaStiXSupport Eigen/PardisoSupport Eigen/QR \
	Eigen/QtAlignedMalloc Eigen/SPQRSupport Eigen/SVD Eigen/Sparse \
	Eigen/SparseCholesky Eigen/SparseCore Eigen/SparseLU \
	Eigen/SparseQR Eigen/StdDeque Eigen/StdList Eigen/StdVector \
	Eigen/SuperLUSupport Eigen/UmfPackSupport \
	Eigen/src/Cholesky/LDLT.h Eigen/src/Cholesky/LLT.h \
	Eigen/src/Cholesky/LLT_LAPACKE.h \
	Eigen/src/CholmodSupport/CholmodSupport.h \
	Eigen/src/Core/Array.h Eigen/src/Core/ArrayBase.h \
	Eigen/src/Core/ArrayWrapper.h Eigen/src/Core/Assign.h \
	Eigen/src/Core/AssignEvaluator.h Eigen/src/Core/Assign_MKL.h \
	Eigen/src/Core/BandMatrix.h Eigen/src/Core/Block.h \
	Eigen/src/Core/BooleanRedux.h \
	Eigen/src/Core/CommaInitializer.h \
	Eigen/src/Core/ConditionEstimator.h \
	Eigen/src/Core/CoreEvaluators.h Eigen/src/Core/CoreIterators.h \
	Eigen/src/Core/CwiseBinaryOp.h Eigen/src/Core/CwiseNullaryOp.h \
	Eigen/src/Core/CwiseTernaryOp.h Eigen/src/Core/CwiseUnaryOp.h \
	Eigen/src/Core/CwiseUnaryView.h Eigen/src/Core/DenseBase.h \
	Eigen/src/Core/DenseCoeffsBase.h Eigen/src/Core/DenseStorage.h \
	Eigen/src/Core/Diagonal.h Eigen/src/Core/DiagonalMatrix.h \
	Eigen/src/Core/DiagonalProduct.h Eigen/src/Core/Dot.h \
	Eigen/src/Core/EigenBase.h Eigen/src/Core/ForceAlignedAccess.h \
	Eigen/src/Core/Fuzzy.h Eigen/src/Core/GeneralProduct.h \
	Eigen/src/Core/GenericPacketMath.h \
	Eigen/src/Core/GlobalFunctions.h Eigen/src/Core/IO.h \
	Eigen/src/Core/Inverse.h Eigen/src/Core/Map.h \
	Eigen/src/Core/MapBase.h Eigen/src/Core/MathFunctions.h \
	Eigen/src/Core/MathFunctionsImpl.h Eigen/src/Core/Matrix.h \
	Eigen/src/Core/MatrixBase.h Eigen/src/Core/NestByValue.h \
	Eigen/src/Core/NoAlias.h Eigen/src/Core/NumTraits.h \
	Eigen/src/Core/PermutationMatrix.h \
	Eigen/src/Core/PlainObjectBase.h Eigen/src/Core/Product.h \
	Eigen/src/Core/ProductEvaluators.h Eigen/src/Core/Random.h \
	Eigen/src/Core/Redux.h Eigen/src/Core/Ref.h \
	Eigen/src/Core/Replicate.h Eigen/src/Core/ReturnByValue.h \
	Eigen/src/Core/Reverse.h Eigen/src/Core/Select.h \
	Eigen/src/Core/SelfAdjointView.h \
	Eigen/src/Core/SelfCwiseBinaryOp.h Eigen/src/Core/Solve.h \
	Eigen/src/Core/SolveTriangular.h Eigen/src/Core/SolverBase.h \
	Eigen/src/Core/StableNorm.h Eigen/src/Core/Stride.h \
	Eigen/src/Core/Swap.h Eigen/src/Core/Transpose.h \
	Eigen/src/Core/Transpositions.h \
	Eigen/src/Core/TriangularMatrix.h Eigen/src/Core/VectorBlock.h \
	Eigen/src/Core/VectorwiseOp.h Eigen/src/Core/Visitor.h \
	Eigen/src/Core/arch/AVX/Complex.h \
	Eigen/src/Core/arch/AVX/MathFunctions.h \
	Eigen/src/Core/arch/AVX/PacketMath.h \
	Eigen/src/Core/arch/AVX/TypeCasting.h \
	Eigen/src/Core/arch/AVX512/MathFunctions.h \
	Eigen/src/Core/arch/AVX512/PacketMath.h \
	Eigen/src/Core/arch/AltiVec/Complex.h \
	Eigen/src/Core/arch/AltiVec/MathFunctions.h \
	Eigen/src/Core/arch/AltiVec/PacketMath.h \
	Eigen/src/Core/arch/CUDA/Complex.h \
	Eigen/src/Core/arch/CUDA/Half.h \
	Eigen/src/Core/arch/CUDA/MathFunctions.h \
	Eigen/src/Core/arch/CUDA/PacketMath.h \
	Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
	Eigen/src/Core/arch/CUDA/TypeCasting.h \
	Eigen/src/Core/arch/Default/Settings.h \
	Eigen/src/Core/arch/NEON/Complex.h \
	Eigen/src/Core/arch/NEON/MathFunctions.h \
	Eigen/src/Core/arch/NEON/PacketMath.h \
	Eigen/src/Core/arch/SSE/Complex.h \
	Eigen/src/Core/arch/SSE/MathFunctions.h \
	Eigen/src/Core/arch/SSE/PacketMath.h \
	Eigen/src/Core/arch/SSE/TypeCasting.h \
	Eigen/src/Core/arch/ZVector/Complex.h \
	Eigen/src/Core/arch/ZVector/MathFunctions.h \
	Eigen/src/Core/arch/ZVector/PacketMath.h \
	Eigen/src/Core/functors/AssignmentFunctors.h \
	Eigen/src/Core/functors/BinaryFunctors.h \
	Eigen/src/Core/functors/NullaryFunctors.h \
	Eigen/src/Core/functors/StlFunctors.h \
	Eigen/src/Core/functors/TernaryFunctors.h \
	Eigen/src/Core/functors/UnaryFunctors.h \
	Eigen/src/Core/products/GeneralBlockPanelKernel.h \
	Eigen/src/Core/products/GeneralMatrixMatrix.h \
	Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
	Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
	Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
	Eigen/src/Core/products/GeneralMatrixVector.h \
	Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
	Eigen/src/Core/products/Parallelizer.h \
	Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
	Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
	Eigen/src/Core/products/SelfadjointMatrixVector.h \
	Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
	Eigen/src/Core/products/SelfadjointProduct.h \
	Eigen/src/Core/products/SelfadjointRank2Update.h \
	Eigen/src/Core/products/TriangularMatrixMatrix.h \
	Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
	Eigen/src/Core/products/TriangularMatrixVector.h \
	Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
	Eigen/src/Core/products/TriangularSolverMatrix.h \
	Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
	Eigen/src/Core/products/TriangularSolverVector.h \
	Eigen/src/Core/util/BlasUtil.h Eigen/src/Core/util/Constants.h \
	Eigen/src/Core/util/DisableStupidWarnings.h \
	Eigen/src/Core/util/ForwardDeclarations.h \
	Eigen/src/Core/util/MKL_support.h Eigen/src/Core/util/Macros.h \
	Eigen/src/Core/util/Memory.h Eigen/src/Core/util/Meta.h \
	Eigen/src/Core/util/NonMPL2.h \
	Eigen/src/Core/util/ReenableStupidWarnings.h \
	Eigen/src/Core/util/StaticAssert.h \
	Eigen/src/Core/util/XprHelper.h \
	Eigen/src/Eigenvalues/ComplexEigenSolver.h \
	Eigen/src/Eigenvalues/ComplexSchur.h \
	Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
	Eigen/src/Eigenvalues/EigenSolver.h \
	Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
	Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
	Eigen/src/Eigenvalues/HessenbergDecomposition.h \
	Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
	Eigen/src/Eigenvalues/RealQZ.h \
	Eigen/src/Eigenvalues/RealSchur.h \
	Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
	Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
	Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
	Eigen/src/Eigenvalues/Tridiagonalization.h \
	Eigen/src/Geometry/AlignedBox.h Eigen/src/Geometry/AngleAxis.h \
	Eigen/src/Geometry/EulerAngles.h \
	Eigen/src/Geometry/Homogeneous.h \
	Eigen/src/Geometry/Hyperplane.h \
	Eigen/src/Geometry/OrthoMethods.h \
	Eigen/src/Geometry/ParametrizedLine.h \
	Eigen/src/Geometry/Quaternion.h \
	Eigen/src/Geometry/Rotation2D.h \
	Eigen/src/Geometry/RotationBase.h Eigen/src/Geometry/Scaling.h \
	Eigen/src/Geometry/Transform.h \
	Eigen/src/Geometry/Translation.h Eigen/src/Geometry/Umeyama.h \
	Eigen/src/Geometry/arch/Geometry_SSE.h \
	Eigen/src/Householder/BlockHouseholder.h \
	Eigen/src/Householder/Householder.h \
	Eigen/src/Householder/HouseholderSequence.h \
	Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
	Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
	Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
	Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
	Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
	Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
	Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
	Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
	Eigen/src/Jacobi/Jacobi.h Eigen/src/LU/Determinant.h \
	Eigen/src/LU/FullPivLU.h Eigen/src/LU/InverseImpl.h \
	Eigen/src/LU/PartialPivLU.h \
	Eigen/src/LU/PartialPivLU_LAPACKE.h \
	Eigen/src/LU/arch/Inverse_SSE.h \
	Eigen/src/MetisSupport/MetisSupport.h \
	Eigen/src/OrderingMethods/Amd.h \
	Eigen/src/OrderingMethods/Eigen_Colamd.h \
	Eigen/src/OrderingMethods/Ordering.h \
	Eigen/src/PaStiXSupport/PaStiXSupport.h \
	Eigen/src/PardisoSupport/PardisoSupport.h \
	Eigen/src/QR/ColPivHouseholderQR.h \
	Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
	Eigen/src/QR/CompleteOrthogonalDecomposition.h \
	Eigen/src/QR/FullPivHouseholderQR.h \
	Eigen/src/QR/HouseholderQR.h \
	Eigen/src/QR/HouseholderQR_LAPACKE.h \
	Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
	Eigen/src/SVD/BDCSVD.h Eigen/src/SVD/JacobiSVD.h \
	Eigen/src/SVD/JacobiSVD_LAPACKE.h Eigen/src/SVD/SVDBase.h \
	Eigen/src/SVD/UpperBidiagonalization.h \
	Eigen/src/SparseCholesky/SimplicialCholesky.h \
	Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
	Eigen/src/SparseCore/AmbiVector.h \
	Eigen/src/SparseCore/CompressedStorage.h \
	Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
	Eigen/src/SparseCore/MappedSparseMatrix.h \
	Eigen/src/SparseCore/SparseAssign.h \
	Eigen/src/SparseCore/SparseBlock.h \
	Eigen/src/SparseCore/SparseColEtree.h \
	Eigen/src/SparseCore/SparseCompressedBase.h \
	Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
	Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
	Eigen/src/SparseCore/SparseDenseProduct.h \
	Eigen/src/SparseCore/SparseDiagonalProduct.h \
	Eigen/src/SparseCore/SparseDot.h \
	Eigen/src/SparseCore/SparseFuzzy.h \
	Eigen/src/SparseCore/SparseMap.h \
	Eigen/src/SparseCore/SparseMatrix.h \
	Eigen/src/SparseCore/SparseMatrixBase.h \
	Eigen/src/SparseCore/SparsePermutation.h \
	Eigen/src/SparseCore/SparseProduct.h \
	Eigen/src/SparseCore/SparseRedux.h \
	Eigen/src/SparseCore/SparseRef.h \
	Eigen/src/SparseCore/SparseSelfAdjointView.h \
	Eigen/src/SparseCore/SparseSolverBase.h \
	Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
	Eigen/src/SparseCore/SparseTranspose.h \
	Eigen/src/SparseCore/SparseTriangularView.h \
	Eigen/src/SparseCore/SparseUtil.h \
	Eigen/src/SparseCore/SparseVector.h \
	Eigen/src/SparseCore/SparseView.h \
	Eigen/src/SparseCore/TriangularSolver.h \
	Eigen/src/SparseLU/SparseLU.h \
	Eigen/src/SparseLU/SparseLUImpl.h \
	Eigen/src/SparseLU/SparseLU_Memory.h \
	Eigen/src/SparseLU/SparseLU_Structs.h \
	Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
	Eigen/src/SparseLU/SparseLU_Utils.h \
	Eigen/src/SparseLU/SparseLU_column_bmod.h \
	Eigen/src/SparseLU/SparseLU_column_dfs.h \
	Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
	Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
	Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
	Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
	Eigen/src/SparseLU/SparseLU_panel_bmod.h \
	Eigen/src/SparseLU/SparseLU_panel_dfs.h \
	Eigen/src/SparseLU/SparseLU_pivotL.h \
	Eigen/src/SparseLU/SparseLU_pruneL.h \
	Eigen/src/SparseLU/SparseLU_relax_snode.h \
	Eigen/src/SparseQR/SparseQR.h Eigen/src/StlSupport/StdDeque.h \
	Eigen/src/StlSupport/StdList.h \
	Eigen/src/StlSupport/StdVector.h \
	Eigen/src/StlSupport/details.h \
	Eigen/src/SuperLUSupport/SuperLUSupport.h \
	Eigen/src/UmfPackSupport/UmfPackSupport.h \
	Eigen/src/misc/Image.h Eigen/src/misc/Kernel.h \
	Eigen/src/misc/RealSvd2x2.h Eigen/src/misc/blas.h \
	Eigen/src/misc/lapack.h Eigen/src/misc/lapacke.h \
	Eigen/src/misc/lapacke_mangling.h \
	Eigen/src/plugins/ArrayCwiseBinaryOps.h \
	Eigen/src/plugins/ArrayCwiseUnaryOps.h \
	Eigen/src/plugins/BlockMethods.h \
	Eigen/src/plugins/CommonCwiseBinaryOps.h \
	Eigen/src/plugins/CommonCwiseUnaryOps.h \
	Eigen/src/plugins/MatrixCwiseBinaryOps.h \
	Eigen/src/plugins/MatrixCwiseUnaryOps.h
noinst_HEADERS = hDist.h \
	bam_endian.h \
	boolParser.h \
	cdsStat.h ncStat.h \
	TypeConversion.h \
	Constant.h \
	kseq.h pException.h tabix.h \
	ksort.h pFile.h \
	genomeLoci.h genomePosition.h IO.h kstring.h \
	codonHelper.h fVcf.h \
	genomeScore.h khash.h \
	boolExprParser.h \
	knetfile.h \
	wFile.h \
	Constant.h MathConstant.h \
	bcf_variant_key.h bcf_filter_arg.h discrete_log_helper.h \
	var_dict.h \
	louvain.h \
	$(EIGEN_HEADER_FILES)

cramore_SOURCES = cramore.cpp \
	Error.cpp PhredHelper.cpp params.cpp commands.cpp \
	dropseq.cpp \
	hts_utils.cpp bcf_ordered_reader.cpp interval.cpp interval_tree.cpp utils.cpp genome_interval.cpp log_tool.cpp estimator.cpp \
	bcf_ordered_writer.cpp reference_sequence.cpp \
	bcf_chunked_reader.cpp genomeChunk.cpp \
	bcf_filtered_reader.cpp \
	bam_ordered_reader.cpp \
	nuclear_pedigree.cpp \
	genotype_concordance.cpp \
	filter.cpp \
	libsvm.cpp libsvm_gkm.cpp \
	cmd_bed_delta_svm_train.cpp \
	cmd_bed_matched_shuffle.cpp \
	cmd_bed_shuffle.cpp \
	cmd_vcf_mendel_dup_conc.cpp cmd_vcf_sample_summary.cpp cmd_vcf_squeeze.cpp cmd_vcf_delta_svm.cpp \
	cmd_vcf_extract.cpp \
	cmd_vcf_svd.cpp tsv_reader.cpp \
	cmd_cram_simul_contam.cpp cmd_cram_verify_pair_id.cpp cmd_cram_sparse_genotype.cpp cmd_cram_flagstat.cpp \
	cmd_cram_procap_detect.cpp cmd_cram_context_indel_analysis.cpp \
	cmd_sc_multinom_em.cpp cmd_sc_multinom_gibbs.cpp cmd_sc_map_stamps.cpp cmd_sc_kallisto_count.cpp \
	Sort.cpp MathVector.cpp MathGold.cpp MathGenMin.cpp MathMatrix.cpp \
	Random.cpp cmd_vcf_infer_ancestry.cpp ancestry_estimator.cpp \
	cmd_vcf_infer_isaf.cpp frequency_estimator.cpp cmd_vcf_update_sites.cpp \
	sam_filtered_reader.cpp sc_drop_seq.cpp \
	sam_ordered_writer.cpp \
	cmd_cram_simuxlet.cpp  \
	cmd_cram_mux_pileup.cpp \
	cmd_cram_dense_genotype.cpp joint_genotype_block_reader.cpp joint_genotype_block_record.cpp variant.cpp variant_manip.cpp augmented_bam_record.cpp sex_ploidy_map.cpp allele.cpp vntr.cpp \
	cmd_fasta_gc_content.cpp fastaGC.cpp \
	cmd_vcf_normalize_depth.cpp \
	cmd_bgen_to_vcf.cpp \
	cmd_cram_verify_bam.cpp contam_estimator.cpp \
	cmd_cram_demuxlet.cpp \
	cmd_vcf_paste_calls.cpp cmd_vcf_merge_candidate_variants.cpp \
	cmd_cram_update_rg.cpp cmd_cram_gtf_util.cpp gtf.cpp \
	cmd_cram_digital_pileup.cpp \
	cmd_cram_freemuxlet.cpp 

cramore_LDADD = $(ALL_LDFLAGS) $(HTSLIB_LIB) $(ALL_LIBS)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
config.mk: $(top_builddir)/config.status $(srcdir)/config.mk.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

cramore$(EXEEXT): $(cramore_OBJECTS) $(cramore_DEPENDENCIES) $(EXTRA_cramore_DEPENDENCIES) 
	@rm -f cramore$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(cramore_OBJECTS) $(cramore_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/Error.Po # am--include-marker
include ./$(DEPDIR)/MathGenMin.Po # am--include-marker
include ./$(DEPDIR)/MathGold.Po # am--include-marker
include ./$(DEPDIR)/MathMatrix.Po # am--include-marker
include ./$(DEPDIR)/MathVector.Po # am--include-marker
include ./$(DEPDIR)/PhredHelper.Po # am--include-marker
include ./$(DEPDIR)/Random.Po # am--include-marker
include ./$(DEPDIR)/Sort.Po # am--include-marker
include ./$(DEPDIR)/allele.Po # am--include-marker
include ./$(DEPDIR)/ancestry_estimator.Po # am--include-marker
include ./$(DEPDIR)/augmented_bam_record.Po # am--include-marker
include ./$(DEPDIR)/bam_ordered_reader.Po # am--include-marker
include ./$(DEPDIR)/bcf_chunked_reader.Po # am--include-marker
include ./$(DEPDIR)/bcf_filtered_reader.Po # am--include-marker
include ./$(DEPDIR)/bcf_ordered_reader.Po # am--include-marker
include ./$(DEPDIR)/bcf_ordered_writer.Po # am--include-marker
include ./$(DEPDIR)/cmd_bed_delta_svm_train.Po # am--include-marker
include ./$(DEPDIR)/cmd_bed_matched_shuffle.Po # am--include-marker
include ./$(DEPDIR)/cmd_bed_shuffle.Po # am--include-marker
include ./$(DEPDIR)/cmd_bgen_to_vcf.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_context_indel_analysis.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_demuxlet.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_dense_genotype.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_digital_pileup.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_flagstat.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_freemuxlet.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_gtf_util.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_mux_pileup.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_procap_detect.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_simul_contam.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_simuxlet.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_sparse_genotype.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_update_rg.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_verify_bam.Po # am--include-marker
include ./$(DEPDIR)/cmd_cram_verify_pair_id.Po # am--include-marker
include ./$(DEPDIR)/cmd_fasta_gc_content.Po # am--include-marker
include ./$(DEPDIR)/cmd_sc_kallisto_count.Po # am--include-marker
include ./$(DEPDIR)/cmd_sc_map_stamps.Po # am--include-marker
include ./$(DEPDIR)/cmd_sc_multinom_em.Po # am--include-marker
include ./$(DEPDIR)/cmd_sc_multinom_gibbs.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_delta_svm.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_extract.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_infer_ancestry.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_infer_isaf.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_mendel_dup_conc.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_merge_candidate_variants.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_normalize_depth.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_paste_calls.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_sample_summary.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_squeeze.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_svd.Po # am--include-marker
include ./$(DEPDIR)/cmd_vcf_update_sites.Po # am--include-marker
include ./$(DEPDIR)/commands.Po # am--include-marker
include ./$(DEPDIR)/contam_estimator.Po # am--include-marker
include ./$(DEPDIR)/cramore.Po # am--include-marker
include ./$(DEPDIR)/dropseq.Po # am--include-marker
include ./$(DEPDIR)/estimator.Po # am--include-marker
include ./$(DEPDIR)/fastaGC.Po # am--include-marker
include ./$(DEPDIR)/filter.Po # am--include-marker
include ./$(DEPDIR)/frequency_estimator.Po # am--include-marker
include ./$(DEPDIR)/genomeChunk.Po # am--include-marker
include ./$(DEPDIR)/genome_interval.Po # am--include-marker
include ./$(DEPDIR)/genotype_concordance.Po # am--include-marker
include ./$(DEPDIR)/gtf.Po # am--include-marker
include ./$(DEPDIR)/hts_utils.Po # am--include-marker
include ./$(DEPDIR)/interval.Po # am--include-marker
include ./$(DEPDIR)/interval_tree.Po # am--include-marker
include ./$(DEPDIR)/joint_genotype_block_reader.Po # am--include-marker
include ./$(DEPDIR)/joint_genotype_block_record.Po # am--include-marker
include ./$(DEPDIR)/libsvm.Po # am--include-marker
include ./$(DEPDIR)/libsvm_gkm.Po # am--include-marker
include ./$(DEPDIR)/log_tool.Po # am--include-marker
include ./$(DEPDIR)/nuclear_pedigree.Po # am--include-marker
include ./$(DEPDIR)/params.Po # am--include-marker
include ./$(DEPDIR)/reference_sequence.Po # am--include-marker
include ./$(DEPDIR)/sam_filtered_reader.Po # am--include-marker
include ./$(DEPDIR)/sam_ordered_writer.Po # am--include-marker
include ./$(DEPDIR)/sc_drop_seq.Po # am--include-marker
include ./$(DEPDIR)/sex_ploidy_map.Po # am--include-marker
include ./$(DEPDIR)/tsv_reader.Po # am--include-marker
include ./$(DEPDIR)/utils.Po # am--include-marker
include ./$(DEPDIR)/variant.Po # am--include-marker
include ./$(DEPDIR)/variant_manip.Po # am--include-marker
include ./$(DEPDIR)/vntr.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/Error.Po
	-rm -f ./$(DEPDIR)/MathGenMin.Po
	-rm -f ./$(DEPDIR)/MathGold.Po
	-rm -f ./$(DEPDIR)/MathMatrix.Po
	-rm -f ./$(DEPDIR)/MathVector.Po
	-rm -f ./$(DEPDIR)/PhredHelper.Po
	-rm -f ./$(DEPDIR)/Random.Po
	-rm -f ./$(DEPDIR)/Sort.Po
	-rm -f ./$(DEPDIR)/allele.Po
	-rm -f ./$(DEPDIR)/ancestry_estimator.Po
	-rm -f ./$(DEPDIR)/augmented_bam_record.Po
	-rm -f ./$(DEPDIR)/bam_ordered_reader.Po
	-rm -f ./$(DEPDIR)/bcf_chunked_reader.Po
	-rm -f ./$(DEPDIR)/bcf_filtered_reader.Po
	-rm -f ./$(DEPDIR)/bcf_ordered_reader.Po
	-rm -f ./$(DEPDIR)/bcf_ordered_writer.Po
	-rm -f ./$(DEPDIR)/cmd_bed_delta_svm_train.Po
	-rm -f ./$(DEPDIR)/cmd_bed_matched_shuffle.Po
	-rm -f ./$(DEPDIR)/cmd_bed_shuffle.Po
	-rm -f ./$(DEPDIR)/cmd_bgen_to_vcf.Po
	-rm -f ./$(DEPDIR)/cmd_cram_context_indel_analysis.Po
	-rm -f ./$(DEPDIR)/cmd_cram_demuxlet.Po
	-rm -f ./$(DEPDIR)/cmd_cram_dense_genotype.Po
	-rm -f ./$(DEPDIR)/cmd_cram_digital_pileup.Po
	-rm -f ./$(DEPDIR)/cmd_cram_flagstat.Po
	-rm -f ./$(DEPDIR)/cmd_cram_freemuxlet.Po
	-rm -f ./$(DEPDIR)/cmd_cram_gtf_util.Po
	-rm -f ./$(DEPDIR)/cmd_cram_mux_pileup.Po
	-rm -f ./$(DEPDIR)/cmd_cram_procap_detect.Po
	-rm -f ./$(DEPDIR)/cmd_cram_simul_contam.Po
	-rm -f ./$(DEPDIR)/cmd_cram_simuxlet.Po
	-rm -f ./$(DEPDIR)/cmd_cram_sparse_genotype.Po
	-rm -f ./$(DEPDIR)/cmd_cram_update_rg.Po
	-rm -f ./$(DEPDIR)/cmd_cram_verify_bam.Po
	-rm -f ./$(DEPDIR)/cmd_cram_verify_pair_id.Po
	-rm -f ./$(DEPDIR)/cmd_fasta_gc_content.Po
	-rm -f ./$(DEPDIR)/cmd_sc_kallisto_count.Po
	-rm -f ./$(DEPDIR)/cmd_sc_map_stamps.Po
	-rm -f ./$(DEPDIR)/cmd_sc_multinom_em.Po
	-rm -f ./$(DEPDIR)/cmd_sc_multinom_gibbs.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_delta_svm.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_extract.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_infer_ancestry.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_infer_isaf.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_mendel_dup_conc.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_merge_candidate_variants.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_normalize_depth.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_paste_calls.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_sample_summary.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_squeeze.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_svd.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_update_sites.Po
	-rm -f ./$(DEPDIR)/commands.Po
	-rm -f ./$(DEPDIR)/contam_estimator.Po
	-rm -f ./$(DEPDIR)/cramore.Po
	-rm -f ./$(DEPDIR)/dropseq.Po
	-rm -f ./$(DEPDIR)/estimator.Po
	-rm -f ./$(DEPDIR)/fastaGC.Po
	-rm -f ./$(DEPDIR)/filter.Po
	-rm -f ./$(DEPDIR)/frequency_estimator.Po
	-rm -f ./$(DEPDIR)/genomeChunk.Po
	-rm -f ./$(DEPDIR)/genome_interval.Po
	-rm -f ./$(DEPDIR)/genotype_concordance.Po
	-rm -f ./$(DEPDIR)/gtf.Po
	-rm -f ./$(DEPDIR)/hts_utils.Po
	-rm -f ./$(DEPDIR)/interval.Po
	-rm -f ./$(DEPDIR)/interval_tree.Po
	-rm -f ./$(DEPDIR)/joint_genotype_block_reader.Po
	-rm -f ./$(DEPDIR)/joint_genotype_block_record.Po
	-rm -f ./$(DEPDIR)/libsvm.Po
	-rm -f ./$(DEPDIR)/libsvm_gkm.Po
	-rm -f ./$(DEPDIR)/log_tool.Po
	-rm -f ./$(DEPDIR)/nuclear_pedigree.Po
	-rm -f ./$(DEPDIR)/params.Po
	-rm -f ./$(DEPDIR)/reference_sequence.Po
	-rm -f ./$(DEPDIR)/sam_filtered_reader.Po
	-rm -f ./$(DEPDIR)/sam_ordered_writer.Po
	-rm -f ./$(DEPDIR)/sc_drop_seq.Po
	-rm -f ./$(DEPDIR)/sex_ploidy_map.Po
	-rm -f ./$(DEPDIR)/tsv_reader.Po
	-rm -f ./$(DEPDIR)/utils.Po
	-rm -f ./$(DEPDIR)/variant.Po
	-rm -f ./$(DEPDIR)/variant_manip.Po
	-rm -f ./$(DEPDIR)/vntr.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/Error.Po
	-rm -f ./$(DEPDIR)/MathGenMin.Po
	-rm -f ./$(DEPDIR)/MathGold.Po
	-rm -f ./$(DEPDIR)/MathMatrix.Po
	-rm -f ./$(DEPDIR)/MathVector.Po
	-rm -f ./$(DEPDIR)/PhredHelper.Po
	-rm -f ./$(DEPDIR)/Random.Po
	-rm -f ./$(DEPDIR)/Sort.Po
	-rm -f ./$(DEPDIR)/allele.Po
	-rm -f ./$(DEPDIR)/ancestry_estimator.Po
	-rm -f ./$(DEPDIR)/augmented_bam_record.Po
	-rm -f ./$(DEPDIR)/bam_ordered_reader.Po
	-rm -f ./$(DEPDIR)/bcf_chunked_reader.Po
	-rm -f ./$(DEPDIR)/bcf_filtered_reader.Po
	-rm -f ./$(DEPDIR)/bcf_ordered_reader.Po
	-rm -f ./$(DEPDIR)/bcf_ordered_writer.Po
	-rm -f ./$(DEPDIR)/cmd_bed_delta_svm_train.Po
	-rm -f ./$(DEPDIR)/cmd_bed_matched_shuffle.Po
	-rm -f ./$(DEPDIR)/cmd_bed_shuffle.Po
	-rm -f ./$(DEPDIR)/cmd_bgen_to_vcf.Po
	-rm -f ./$(DEPDIR)/cmd_cram_context_indel_analysis.Po
	-rm -f ./$(DEPDIR)/cmd_cram_demuxlet.Po
	-rm -f ./$(DEPDIR)/cmd_cram_dense_genotype.Po
	-rm -f ./$(DEPDIR)/cmd_cram_digital_pileup.Po
	-rm -f ./$(DEPDIR)/cmd_cram_flagstat.Po
	-rm -f ./$(DEPDIR)/cmd_cram_freemuxlet.Po
	-rm -f ./$(DEPDIR)/cmd_cram_gtf_util.Po
	-rm -f ./$(DEPDIR)/cmd_cram_mux_pileup.Po
	-rm -f ./$(DEPDIR)/cmd_cram_procap_detect.Po
	-rm -f ./$(DEPDIR)/cmd_cram_simul_contam.Po
	-rm -f ./$(DEPDIR)/cmd_cram_simuxlet.Po
	-rm -f ./$(DEPDIR)/cmd_cram_sparse_genotype.Po
	-rm -f ./$(DEPDIR)/cmd_cram_update_rg.Po
	-rm -f ./$(DEPDIR)/cmd_cram_verify_bam.Po
	-rm -f ./$(DEPDIR)/cmd_cram_verify_pair_id.Po
	-rm -f ./$(DEPDIR)/cmd_fasta_gc_content.Po
	-rm -f ./$(DEPDIR)/cmd_sc_kallisto_count.Po
	-rm -f ./$(DEPDIR)/cmd_sc_map_stamps.Po
	-rm -f ./$(DEPDIR)/cmd_sc_multinom_em.Po
	-rm -f ./$(DEPDIR)/cmd_sc_multinom_gibbs.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_delta_svm.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_extract.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_infer_ancestry.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_infer_isaf.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_mendel_dup_conc.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_merge_candidate_variants.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_normalize_depth.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_paste_calls.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_sample_summary.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_squeeze.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_svd.Po
	-rm -f ./$(DEPDIR)/cmd_vcf_update_sites.Po
	-rm -f ./$(DEPDIR)/commands.Po
	-rm -f ./$(DEPDIR)/contam_estimator.Po
	-rm -f ./$(DEPDIR)/cramore.Po
	-rm -f ./$(DEPDIR)/dropseq.Po
	-rm -f ./$(DEPDIR)/estimator.Po
	-rm -f ./$(DEPDIR)/fastaGC.Po
	-rm -f ./$(DEPDIR)/filter.Po
	-rm -f ./$(DEPDIR)/frequency_estimator.Po
	-rm -f ./$(DEPDIR)/genomeChunk.Po
	-rm -f ./$(DEPDIR)/genome_interval.Po
	-rm -f ./$(DEPDIR)/genotype_concordance.Po
	-rm -f ./$(DEPDIR)/gtf.Po
	-rm -f ./$(DEPDIR)/hts_utils.Po
	-rm -f ./$(DEPDIR)/interval.Po
	-rm -f ./$(DEPDIR)/interval_tree.Po
	-rm -f ./$(DEPDIR)/joint_genotype_block_reader.Po
	-rm -f ./$(DEPDIR)/joint_genotype_block_record.Po
	-rm -f ./$(DEPDIR)/libsvm.Po
	-rm -f ./$(DEPDIR)/libsvm_gkm.Po
	-rm -f ./$(DEPDIR)/log_tool.Po
	-rm -f ./$(DEPDIR)/nuclear_pedigree.Po
	-rm -f ./$(DEPDIR)/params.Po
	-rm -f ./$(DEPDIR)/reference_sequence.Po
	-rm -f ./$(DEPDIR)/sam_filtered_reader.Po
	-rm -f ./$(DEPDIR)/sam_ordered_writer.Po
	-rm -f ./$(DEPDIR)/sc_drop_seq.Po
	-rm -f ./$(DEPDIR)/sex_ploidy_map.Po
	-rm -f ./$(DEPDIR)/tsv_reader.Po
	-rm -f ./$(DEPDIR)/utils.Po
	-rm -f ./$(DEPDIR)/variant.Po
	-rm -f ./$(DEPDIR)/variant_manip.Po
	-rm -f ./$(DEPDIR)/vntr.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
